AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Stack Inventory System <DATE>

Parameters:
  TopicName:
    Type: String

Resources:
  InventoryTopic:
    Type: "AWS::SNS::Topic2"
    Properties:
      TopicName: {Ref: TopicName}

Outputs:
  InventoryTopicArn:
    Description: Created InventoryTopic ARN
    Value:
      Ref: InventoryTopic
